library(tidyverse)
library(readxl)
library(ggplot2)
library(lubridate)
year1 <- read_xlsx("/Users/nourhanghanima/Downloads/online_retail_II.xlsx", sheet = "Year 2009-2010")
year2 <- read_xlsx("/Users/nourhanghanima/Downloads/online_retail_II.xlsx", sheet = "Year 2010-2011")
retail_data <- bind_rows(year1, year2)
View(retail_data)
#there are negative values for quantity
summary(retail_data)
retail_data <- retail_data |>
  filter(!is.na(`Customer ID`), Quantity > 0, Price > 0)

#removing canceled orders 
retail_data <- retail_data |>
  filter(!str_starts(Invoice, "C"))

#the name for Ireland is EIRE, changing it
retail_data <- retail_data |>
  mutate(
    Country = case_match(Country,
                         "EIRE" ~ "Ireland",
                         .default = Country
    )
  )
#calculating revenue by country 
revenue_by_country <- retail_data |> select (Quantity, Price, Country) |>
  mutate (Revenue = Quantity * Price) |>
  group_by(Country) |>
  summarize(revenue_country = sum(Revenue)) |>
  arrange(desc(revenue_country))
View(revenue_by_country)
revenue_by_country |>
  slice_max(revenue_country, n = 10) |>
  ggplot(aes(x = reorder(Country, revenue_country), y = revenue_country)) +
  geom_col() +
  coord_flip() +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Country", y = "Revenue", title = "Top 10 Countries by Revenue")
#UK highest revenue producing country, by a big margin 

#seeing how many orders per customer ID
retail_data <- retail_data |>
  rename( customer_id = "Customer ID") 

retail_data <- retail_data |> 
  group_by(customer_id) |>
  mutate(n_orders = n_distinct(Invoice)) |>
  ungroup()
  
View(retail_data)
#seeing customer with highest number of orders and where are they from 
wtf <- retail_data |>
  select(n_orders, customer_id, Country) |>
  distinct(customer_id, Country, n_orders) |>
  arrange(desc(n_orders))
  
# sum of revenue generated by each customer and calculating the recency for each customer
snapshot_date <- max(retail_data$InvoiceDate, na.rm = TRUE) 
rfm <- retail_data |>
  mutate(revenue = Quantity * Price) |>
  group_by(customer_id) |>
  summarize(
    frequency = n_distinct(Invoice),
    monetary  = sum(revenue),
    recency   = as.numeric(snapshot_date - max(InvoiceDate), units = "days")
  )

View(rfm)


#creating scores for revenue, recency, and frequency
rfm <- rfm |>
  mutate(
    r_score = ntile(desc(recency), 5),
    f_score = ntile(frequency, 5),
    m_score = ntile(monetary, 5),
    segment = case_when(
      r_score >= 4 &f_score >= 4 & m_score >= 4 ~ "Long time regular", 
      r_score >= 3 & f_score >= 3 ~ "Loyal",
      r_score >= 4 & f_score <= 2 ~ "New Customers",
      r_score <= 2 & f_score >= 4 ~ "At Risk",
      r_score <= 2 & f_score <= 2 ~ "Lost",
      .default = "Other"
    )
  )


cohort_try <- retail_data |>
  group_by(customer_id) |>
  arrange(InvoiceDate, .by_group = TRUE) |>
  slice_head(n = 1) |>
  ungroup()|>
  mutate(
    cohort_month = floor_date(InvoiceDate, "month")
  )
  

retail_data <- retail_data |>
  left_join(cohort_try |> select(customer_id, cohort_month), by = "customer_id")

retail_data <- retail_data |>
  mutate(order_month = floor_date(InvoiceDate, "month"))


retail_data <- retail_data |>
  mutate(
    cohort_index = (year(order_month) - year(cohort_month)) * 12 +
      (month(order_month) - month(cohort_month))
  )

View(retail_data)

#getting the number of customers in each cohort, per year, per month 
cohort_counts <- retail_data |>
  distinct(customer_id, cohort_month, cohort_index) |>
  count(cohort_month, cohort_index, name = "n_customers")

cohort_sizes <- cohort_counts |>
  filter(cohort_index == 0) |>
  select(cohort_month, cohort_size = n_customers)

cohort_retention <- cohort_counts |>
  left_join(cohort_sizes, by = "cohort_month") |>
  mutate(retention = n_customers / cohort_size)

cohort_retention |>
  ggplot(aes(x = cohort_index, y = factor(cohort_month), fill = retention)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "white", high = "steelblue", labels = scales::percent) +
  labs(
    x = "Months Since First Purchase",
    y = "Cohort (First Purchase Month)",
    fill = "Retention",
    title = "Customer Retention by Monthly Cohort"
  ) +
  theme_minimal()

